### ISSUE TITLE
Add "pipe bob tut deed" names

### ISSUE THREAD

**Issue by fallenpegasus** [adiabatic/Configuratronic-Quikscript-Cheat-Sheet#1]
I've been memorizing Quickscript with those names instead of Read's.

**Comment by adiabatic** [comment]
One of the primary uses of the CQCS is to help people figure out what characters others are referring to on the mailing list and how to pronounce them. I haven't seen "pipe, bob, …" in the wild aside from one particular image showing all the characters. Given all this, it's not clear to me what the benefit of memorizing "pipe, bob, …" is.

My preference is to keep the metalanguage of Quickscript from splintering, and to keep the number of confusingly similar options in the CQCS to a minimum.

**Comment by fallenpegasus** [comment]
The "pipe, bob, ..." sequence seems to have more stable pronunciations
over multiple dialects than Read's Words.

On Fri, Apr 6, 2012 at 5:18 PM, adiabatic
reply@reply.github.com
wrote:
