### ISSUE TITLE
Add Lock, Llan, Excite and Exam

### ISSUE THREAD

**Issue by ReNardier** [adiabatic/Configuratronic-Quikscript-Cheat-Sheet#3]
here is a little something i whipped up for some missing letters from the chart, the read names are like in the book

<table>
    <tr class='qsJerome'>
        <td>ç
        <td>æ
        <td>è
        <td>é
    <tr class='qsThoth'>
        <td>K
        <td>L
        <td>X
        <td>x
    <tr class='ipa'>
        <td>/x/
        <td>/ɬ/
        <td>/ks/
        <td>/gz/
    <tr class='xs'>
        <td>/x/
        <td>/K/
        <td>/ks/
        <td>/gz/
    <tr class='readName'>
        <td>loch
        <td>llan
        <td>excite
        <td>examine
    <tr class='pua'>
        <td>E669
        <td>E66A
        <td>E66B
        <td>E66C
</table>

**Comment by adiabatic** [comment]
I really should add these. Thanks!
